// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ConvertFiles(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<Array<string>>;

export function SetCopyLrc(arg1:boolean):Promise<void>;

export function SetFilenamePattern(arg1:string):Promise<void>;

export function SetOutputDir(arg1:string):Promise<void>;
