// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SetFilenamePattern(arg1) {
  return window['go']['main']['App']['SetFilenamePattern'](arg1);
}

export function SetOutputDir(arg1) {
  return window['go']['main']['App']['SetOutputDir'](arg1);
}
